// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGJUS2XZV8tFk3ZiLfHh41l1FrSaOhsMM',
    appId: '1:720414373492:web:3ac09d1d704ef493410321',
    messagingSenderId: '720414373492',
    projectId: 'flutter-chat-app-d9b2a',
    authDomain: 'flutter-chat-app-d9b2a.firebaseapp.com',
    storageBucket: 'flutter-chat-app-d9b2a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzkS2dJx3jLCZE1DY6LXoR1t3chAYuVGY',
    appId: '1:720414373492:android:4ab9ea1d32400369410321',
    messagingSenderId: '720414373492',
    projectId: 'flutter-chat-app-d9b2a',
    storageBucket: 'flutter-chat-app-d9b2a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbJXGrY_GtWJM4ejbvEejy-tq0MeBzD-U',
    appId: '1:720414373492:ios:9c86a093ba3e9e39410321',
    messagingSenderId: '720414373492',
    projectId: 'flutter-chat-app-d9b2a',
    storageBucket: 'flutter-chat-app-d9b2a.appspot.com',
    iosClientId: '720414373492-b56tre1btefa9rqdfjufte9830hd64fe.apps.googleusercontent.com',
    iosBundleId: 'com.example.authblock',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbJXGrY_GtWJM4ejbvEejy-tq0MeBzD-U',
    appId: '1:720414373492:ios:9c86a093ba3e9e39410321',
    messagingSenderId: '720414373492',
    projectId: 'flutter-chat-app-d9b2a',
    storageBucket: 'flutter-chat-app-d9b2a.appspot.com',
    iosClientId: '720414373492-b56tre1btefa9rqdfjufte9830hd64fe.apps.googleusercontent.com',
    iosBundleId: 'com.example.authblock',
  );
}
